name: MSBuild

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: msbuild /t:Restore /p:Platform=x64 PatchWork.sln

    - name: Build Debug
      run: msbuild /m /p:Platform=x64 /p:Configuration=Debug PatchWork.sln

    - name: Build Release
      run: msbuild /m /p:Platform=x64 /p:Configuration=Release PatchWork.sln

    - name: Upload Debug artifact
      uses: actions/upload-artifact@v4
      with:
        name: PatchWork-Debug
        path: x64\Debug\PatchWork.dll

    - name: Upload Release artifact
      uses: actions/upload-artifact@v4
      with:
        name: PatchWork-Release
        path: x64\Release\PatchWork.dll
